### ISSUE TITLE
show we have a logger?

### ISSUE THREAD

**Issue by zahmadsaleem** [shiblon/entroq#43]
Currently I get such logs in between my app logs, and I have no way to trace it back to the connected worker. 

```
2023/06/18 20:08:26 Rewriting delete version 1 => 2
```

Does it make sense to add a logger? 
How would you suggest implementing it? I can implement and submit a PR

**Comment by shiblon** [comment]
Those log lines are actually pretty spammy and probably not necessary except for debugging. Would you be solving the spam problem with a logger, or some other set of problems? The best fix might be to just remove those log lines, since they don't tell you anything useful.

**Comment by zahmadsaleem** [comment]
I would like to capture some internal errors from the workers etc.
But as of the spam, I don't find any use for it and it might be an easy solution to just comment them out

**Comment by shiblon** [comment]
9fbe40adf813cc7343af6450f8a897574e5c88f0
